### ISSUE TITLE
gem won't build with 1.4 update

### ISSUE THREAD

**Issue by ebdavison** [hammackj/risu#26]
Just pulled the new 1.4 code and tried 'gem build nessusdb.gemspec' and get the following error:

```
Invalid gemspec in [nessusdb.gemspec]: Malformed version number string 1.4-dev
ERROR: While executing gem ... (NoMethodError)
    undefined method `mark_version' for nil:NilClass
```
